<a href="https://colab.research.google.com/github/aliabidzaidi/pytorch-testing/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [3]:
!pip show torch

Name: torch
Version: 2.5.1+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, fastai, peft, sentence-transformers, timm, torchaudio, torchvision


## Tensors

- Tensor is a multidimensional matrix contiaing elements similar to numpy arrays
- default data type of float32
- More suitable for deep learning than a numpy array

### Python lists

In [4]:
python_list = [1,2,3,4]
python_multidimensional_list = [[1,2,3,4], [4,5,6,7]]

print(python_list)
print(python_multidimensional_list)

[1, 2, 3, 4]
[[1, 2, 3, 4], [4, 5, 6, 7]]


### Numpy arrays

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.22910662, 0.19808774, 0.94693244, 0.4674345 ],
       [0.88491733, 0.26750782, 0.11705812, 0.81059307],
       [0.02134009, 0.17852231, 0.2974773 , 0.84067192]])

In [6]:
np1.dtype

dtype('float64')

### Tensors
https://pytorch.org/docs/stable/tensors.html

In [7]:
tensor_2d = torch.randn(3,4)
# tensor_2d = torch.randn(3,4, dtype=torch.float64)
tensor_2d

tensor([[ 0.6484, -0.9013,  0.7254,  0.1322],
        [-0.0494,  0.4447,  0.3536, -0.3453],
        [ 1.2466,  0.0497,  1.8542,  0.7835]])

In [8]:
tensor_3d = torch.ones(2,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
# Copy numpy array to tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2291, 0.1981, 0.9469, 0.4674],
        [0.8849, 0.2675, 0.1171, 0.8106],
        [0.0213, 0.1785, 0.2975, 0.8407]], dtype=torch.float64)